import type {
  ClientSatisfactionSummary,
  Survey,
  SurveyQuestion,
} from "./-types"

export const surveyQuestions: SurveyQuestion[] = [
  {
    id: "q1",
    text: "How satisfied are you with our communication?",
    category: "Communication",
  },
  {
    id: "q2",
    text: "How would you rate the quality of our deliverables?",
    category: "Quality",
  },
  {
    id: "q3",
    text: "How satisfied are you with our timeliness?",
    category: "Timeliness",
  },
  {
    id: "q4",
    text: "How likely are you to recommend our services?",
    category: "Loyalty",
  },
  {
    id: "q5",
    text: "How satisfied are you with our responsiveness?",
    category: "Support",
  },
]

export const mockSurveys: Survey[] = [
  {
    id: 1,
    token: "srv_abc123def456",
    client_id: 1,
    status: "completed",
    created_at: "2026-07-15T10:00:00Z",
    completed_at: "2026-07-16T14:30:00Z",
    responses: [
      { question_id: "q1", score: 4 },
      { question_id: "q2", score: 5 },
      { question_id: "q3", score: 4 },
      { question_id: "q4", score: 5 },
      { question_id: "q5", score: 4 },
    ],
    average_score: 4.4,
  },
  {
    id: 2,
    token: "srv_ghi789jkl012",
    client_id: 1,
    status: "completed",
    created_at: "2026-08-10T09:00:00Z",
    completed_at: "2026-08-12T11:00:00Z",
    responses: [
      { question_id: "q1", score: 5 },
      { question_id: "q2", score: 5 },
      { question_id: "q3", score: 4 },
      { question_id: "q4", score: 5 },
      { question_id: "q5", score: 5 },
    ],
    average_score: 4.8,
  },
  {
    id: 3,
    token: "srv_mno345pqr678",
    client_id: 1,
    status: "pending",
    created_at: "2026-08-20T08:00:00Z",
    completed_at: null,
    responses: [],
    average_score: null,
  },
  {
    id: 4,
    token: "srv_stu901vwx234",
    client_id: 2,
    status: "completed",
    created_at: "2026-07-01T10:00:00Z",
    completed_at: "2026-07-05T16:00:00Z",
    responses: [
      { question_id: "q1", score: 3 },
      { question_id: "q2", score: 4 },
      { question_id: "q3", score: 3 },
      { question_id: "q4", score: 4 },
      { question_id: "q5", score: 3 },
    ],
    average_score: 3.4,
  },
  {
    id: 5,
    token: "srv_yza567bcd890",
    client_id: 2,
    status: "completed",
    created_at: "2026-08-01T10:00:00Z",
    completed_at: "2026-08-04T09:00:00Z",
    responses: [
      { question_id: "q1", score: 4 },
      { question_id: "q2", score: 4 },
      { question_id: "q3", score: 4 },
      { question_id: "q4", score: 4 },
      { question_id: "q5", score: 4 },
    ],
    average_score: 4.0,
  },
  {
    id: 6,
    token: "srv_efg123hij456",
    client_id: 3,
    status: "expired",
    created_at: "2026-06-01T10:00:00Z",
    completed_at: null,
    responses: [],
    average_score: null,
  },
  {
    id: 7,
    token: "srv_klm789nop012",
    client_id: 3,
    status: "completed",
    created_at: "2026-07-20T10:00:00Z",
    completed_at: "2026-07-22T14:00:00Z",
    responses: [
      { question_id: "q1", score: 5 },
      { question_id: "q2", score: 5 },
      { question_id: "q3", score: 5 },
      { question_id: "q4", score: 5 },
      { question_id: "q5", score: 5 },
    ],
    average_score: 5.0,
  },
  {
    id: 8,
    token: "srv_qrs345tuv678",
    client_id: 4,
    status: "completed",
    created_at: "2026-08-05T10:00:00Z",
    completed_at: "2026-08-07T11:00:00Z",
    responses: [
      { question_id: "q1", score: 2 },
      { question_id: "q2", score: 3 },
      { question_id: "q3", score: 2 },
      { question_id: "q4", score: 3 },
      { question_id: "q5", score: 2 },
    ],
    average_score: 2.4,
  },
  {
    id: 9,
    token: "srv_wxy901zab234",
    client_id: 5,
    status: "pending",
    created_at: "2026-08-22T10:00:00Z",
    completed_at: null,
    responses: [],
    average_score: null,
  },
]

export const mockClientSummaries: ClientSatisfactionSummary[] = [
  {
    id: 1,
    company: {
      name: "Acme Corporation",
      industry: "Technology",
      address: "123 Innovation Blvd, Tech City, TC 10001",
      phone: "+1 (555) 123-4567",
      website: "www.acmecorp.com",
    },
    primary_contact: { name: "John Smith", title: "CTO" },
    total_surveys: 3,
    completed_surveys: 2,
    pending_surveys: 1,
    last_survey_date: "2026-08-12T11:00:00Z",
    average_score: 4.6,
    trend: "up",
  },
  {
    id: 2,
    company: {
      name: "Global Industries",
      industry: "Manufacturing",
      address: "456 Industrial Way, Factory Town, FT 20002",
      phone: "+1 (555) 234-5678",
      website: "www.globalindustries.com",
    },
    primary_contact: { name: "Sarah Johnson", title: "Operations Director" },
    total_surveys: 2,
    completed_surveys: 2,
    pending_surveys: 0,
    last_survey_date: "2026-08-04T09:00:00Z",
    average_score: 3.7,
    trend: "up",
  },
  {
    id: 3,
    company: {
      name: "Stark Enterprises",
      industry: "Defense",
      address: "789 Tower Ave, Malibu, CA 90265",
      phone: "+1 (555) 345-6789",
      website: "www.starkenterprises.com",
    },
    primary_contact: { name: "Tony Stark", title: "CEO" },
    total_surveys: 2,
    completed_surveys: 1,
    pending_surveys: 0,
    last_survey_date: "2026-07-22T14:00:00Z",
    average_score: 5.0,
    trend: "stable",
  },
  {
    id: 4,
    company: {
      name: "Wayne Industries",
      industry: "Conglomerate",
      address: "321 Manor Drive, Gotham, NJ 07001",
      phone: "+1 (555) 456-7890",
      website: "www.wayneindustries.com",
    },
    primary_contact: { name: "Bruce Wayne", title: "CEO" },
    total_surveys: 1,
    completed_surveys: 1,
    pending_surveys: 0,
    last_survey_date: "2026-08-07T11:00:00Z",
    average_score: 2.4,
    trend: "down",
  },
  {
    id: 5,
    company: {
      name: "Oscorp Industries",
      industry: "Pharmaceuticals",
      address: "654 Science Park, New York, NY 10001",
      phone: "+1 (555) 567-8901",
      website: "www.oscorp.com",
    },
    primary_contact: { name: "Norman Osborn", title: "CEO" },
    total_surveys: 1,
    completed_surveys: 0,
    pending_surveys: 1,
    last_survey_date: null,
    average_score: null,
    trend: null,
  },
  {
    id: 6,
    company: {
      name: "Umbrella Corp",
      industry: "Biotechnology",
      address: "987 Research Blvd, Raccoon City, CA 90001",
      phone: "+1 (555) 678-9012",
      website: "www.umbrellacorp.com",
    },
    primary_contact: { name: "Albert Wesker", title: "Director" },
    total_surveys: 0,
    completed_surveys: 0,
    pending_surveys: 0,
    last_survey_date: null,
    average_score: null,
    trend: null,
  },
]