/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as SalesRouteRouteImport } from './routes/sales/route'
import { Route as AdminLeadAndClientRouteRouteImport } from './routes/admin/lead-and-client/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SalesLeadAndClientRouteRouteImport } from './routes/sales/lead-and-client/route'
import { Route as SurveyTokenRouteImport } from './routes/survey/$token'
import { Route as AdminAccountIndexRouteImport } from './routes/admin/account/index'
import { Route as AdminAuditLogIndexRouteImport } from './routes/admin/audit-log/index'
import { Route as AdminCommunicationsIndexRouteImport } from './routes/admin/communications/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin/opportunities/index'
import { Route as AdminRemindersIndexRouteImport } from './routes/admin/reminders/index'
import { Route as AdminSatisfactionIndexRouteImport } from './routes/admin/satisfaction/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as SalesAccountIndexRouteImport } from './routes/sales/account/index'
import { Route as SalesCommunicationsIndexRouteImport } from './routes/sales/communications/index'
import { Route as SalesOpportunitiesIndexRouteImport } from './routes/sales/opportunities/index'
import { Route as SalesRemindersIndexRouteImport } from './routes/sales/reminders/index'
import { Route as SalesSatisfactionIndexRouteImport } from './routes/sales/satisfaction/index'
import { Route as AdminClientClientIdIndexRouteImport } from './routes/admin/client/$clientId/index'
import { Route as AdminCommunicationsCommunicationIdIndexRouteImport } from './routes/admin/communications/$communicationId/index'
import { Route as AdminCommunicationsCreateIndexRouteImport } from './routes/admin/communications/create/index'
import { Route as AdminLeadAndClientClientsIndexRouteImport } from './routes/admin/lead-and-client/clients/index'
import { Route as AdminLeadAndClientLeadsIndexRouteImport } from './routes/admin/lead-and-client/leads/index'
import { Route as AdminLeadLeadIdIndexRouteImport } from './routes/admin/lead/$leadId/index'
import { Route as AdminLeadCreateIndexRouteImport } from './routes/admin/lead/create/index'
import { Route as AdminOpportunityOpportunityIdIndexRouteImport } from './routes/admin/opportunity/$opportunityId/index'
import { Route as AdminOpportunityCreateIndexRouteImport } from './routes/admin/opportunity/create/index'
import { Route as AdminRemindersReminderIdIndexRouteImport } from './routes/admin/reminders/$reminderId/index'
import { Route as AdminRemindersCreateIndexRouteImport } from './routes/admin/reminders/create/index'
import { Route as AdminSatisfactionClientIdIndexRouteImport } from './routes/admin/satisfaction/$clientId/index'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'
import { Route as AdminUsersCreateIndexRouteImport } from './routes/admin/users/create/index'
import { Route as SalesClientClientIdIndexRouteImport } from './routes/sales/client/$clientId/index'
import { Route as SalesCommunicationsCommunicationIdIndexRouteImport } from './routes/sales/communications/$communicationId/index'
import { Route as SalesCommunicationsCreateIndexRouteImport } from './routes/sales/communications/create/index'
import { Route as SalesLeadAndClientClientsIndexRouteImport } from './routes/sales/lead-and-client/clients/index'
import { Route as SalesLeadAndClientLeadsIndexRouteImport } from './routes/sales/lead-and-client/leads/index'
import { Route as SalesLeadLeadIdIndexRouteImport } from './routes/sales/lead/$leadId/index'
import { Route as SalesOpportunityOpportunityIdIndexRouteImport } from './routes/sales/opportunity/$opportunityId/index'
import { Route as SalesOpportunityCreateIndexRouteImport } from './routes/sales/opportunity/create/index'
import { Route as SalesRemindersReminderIdIndexRouteImport } from './routes/sales/reminders/$reminderId/index'
import { Route as SalesRemindersCreateIndexRouteImport } from './routes/sales/reminders/create/index'
import { Route as SalesSatisfactionClientIdIndexRouteImport } from './routes/sales/satisfaction/$clientId/index'
import { Route as AdminOpportunityOpportunityIdEditIndexRouteImport } from './routes/admin/opportunity/$opportunityId/edit/index'
import { Route as SalesOpportunityOpportunityIdEditIndexRouteImport } from './routes/sales/opportunity/$opportunityId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRouteRoute = SalesRouteRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadAndClientRouteRoute = AdminLeadAndClientRouteRouteImport.update({
  id: '/lead-and-client',
  path: '/lead-and-client',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLeadAndClientRouteRoute = SalesLeadAndClientRouteRouteImport.update({
  id: '/lead-and-client',
  path: '/lead-and-client',
  getParentRoute: () => SalesRouteRoute,
} as any)
const SurveyTokenRoute = SurveyTokenRouteImport.update({
  id: '/survey/$token',
  path: '/survey/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountIndexRoute = AdminAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogIndexRoute = AdminAuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunicationsIndexRoute =
  AdminCommunicationsIndexRouteImport.update({
    id: '/communications/',
    path: '/communications/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRemindersIndexRoute = AdminRemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSatisfactionIndexRoute = AdminSatisfactionIndexRouteImport.update({
  id: '/satisfaction/',
  path: '/satisfaction/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SalesAccountIndexRoute = SalesAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => SalesRouteRoute,
} as any)
const SalesCommunicationsIndexRoute =
  SalesCommunicationsIndexRouteImport.update({
    id: '/communications/',
    path: '/communications/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const SalesOpportunitiesIndexRoute = SalesOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => SalesRouteRoute,
} as any)
const SalesRemindersIndexRoute = SalesRemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => SalesRouteRoute,
} as any)
const SalesSatisfactionIndexRoute = SalesSatisfactionIndexRouteImport.update({
  id: '/satisfaction/',
  path: '/satisfaction/',
  getParentRoute: () => SalesRouteRoute,
} as any)
const AdminClientClientIdIndexRoute =
  AdminClientClientIdIndexRouteImport.update({
    id: '/client/$clientId/',
    path: '/client/$clientId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCommunicationsCommunicationIdIndexRoute =
  AdminCommunicationsCommunicationIdIndexRouteImport.update({
    id: '/communications/$communicationId/',
    path: '/communications/$communicationId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCommunicationsCreateIndexRoute =
  AdminCommunicationsCreateIndexRouteImport.update({
    id: '/communications/create/',
    path: '/communications/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLeadAndClientClientsIndexRoute =
  AdminLeadAndClientClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AdminLeadAndClientRouteRoute,
  } as any)
const AdminLeadAndClientLeadsIndexRoute =
  AdminLeadAndClientLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AdminLeadAndClientRouteRoute,
  } as any)
const AdminLeadLeadIdIndexRoute = AdminLeadLeadIdIndexRouteImport.update({
  id: '/lead/$leadId/',
  path: '/lead/$leadId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadCreateIndexRoute = AdminLeadCreateIndexRouteImport.update({
  id: '/lead/create/',
  path: '/lead/create/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOpportunityOpportunityIdIndexRoute =
  AdminOpportunityOpportunityIdIndexRouteImport.update({
    id: '/opportunity/$opportunityId/',
    path: '/opportunity/$opportunityId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOpportunityCreateIndexRoute =
  AdminOpportunityCreateIndexRouteImport.update({
    id: '/opportunity/create/',
    path: '/opportunity/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRemindersReminderIdIndexRoute =
  AdminRemindersReminderIdIndexRouteImport.update({
    id: '/reminders/$reminderId/',
    path: '/reminders/$reminderId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRemindersCreateIndexRoute =
  AdminRemindersCreateIndexRouteImport.update({
    id: '/reminders/create/',
    path: '/reminders/create/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminSatisfactionClientIdIndexRoute =
  AdminSatisfactionClientIdIndexRouteImport.update({
    id: '/satisfaction/$clientId/',
    path: '/satisfaction/$clientId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersCreateIndexRoute = AdminUsersCreateIndexRouteImport.update({
  id: '/users/create/',
  path: '/users/create/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SalesClientClientIdIndexRoute =
  SalesClientClientIdIndexRouteImport.update({
    id: '/client/$clientId/',
    path: '/client/$clientId/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const SalesCommunicationsCommunicationIdIndexRoute =
  SalesCommunicationsCommunicationIdIndexRouteImport.update({
    id: '/communications/$communicationId/',
    path: '/communications/$communicationId/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const SalesCommunicationsCreateIndexRoute =
  SalesCommunicationsCreateIndexRouteImport.update({
    id: '/communications/create/',
    path: '/communications/create/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const SalesLeadAndClientClientsIndexRoute =
  SalesLeadAndClientClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => SalesLeadAndClientRouteRoute,
  } as any)
const SalesLeadAndClientLeadsIndexRoute =
  SalesLeadAndClientLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => SalesLeadAndClientRouteRoute,
  } as any)
const SalesLeadLeadIdIndexRoute = SalesLeadLeadIdIndexRouteImport.update({
  id: '/lead/$leadId/',
  path: '/lead/$leadId/',
  getParentRoute: () => SalesRouteRoute,
} as any)
const SalesOpportunityOpportunityIdIndexRoute =
  SalesOpportunityOpportunityIdIndexRouteImport.update({
    id: '/opportunity/$opportunityId/',
    path: '/opportunity/$opportunityId/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const SalesOpportunityCreateIndexRoute =
  SalesOpportunityCreateIndexRouteImport.update({
    id: '/opportunity/create/',
    path: '/opportunity/create/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const SalesRemindersReminderIdIndexRoute =
  SalesRemindersReminderIdIndexRouteImport.update({
    id: '/reminders/$reminderId/',
    path: '/reminders/$reminderId/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const SalesRemindersCreateIndexRoute =
  SalesRemindersCreateIndexRouteImport.update({
    id: '/reminders/create/',
    path: '/reminders/create/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const SalesSatisfactionClientIdIndexRoute =
  SalesSatisfactionClientIdIndexRouteImport.update({
    id: '/satisfaction/$clientId/',
    path: '/satisfaction/$clientId/',
    getParentRoute: () => SalesRouteRoute,
  } as any)
const AdminOpportunityOpportunityIdEditIndexRoute =
  AdminOpportunityOpportunityIdEditIndexRouteImport.update({
    id: '/opportunity/$opportunityId/edit/',
    path: '/opportunity/$opportunityId/edit/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const SalesOpportunityOpportunityIdEditIndexRoute =
  SalesOpportunityOpportunityIdEditIndexRouteImport.update({
    id: '/opportunity/$opportunityId/edit/',
    path: '/opportunity/$opportunityId/edit/',
    getParentRoute: () => SalesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sales': typeof SalesRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/sales/lead-and-client': typeof SalesLeadAndClientRouteRouteWithChildren
  '/survey/$token': typeof SurveyTokenRoute
  '/login/': typeof LoginIndexRoute
  '/admin/account/': typeof AdminAccountIndexRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
  '/admin/communications/': typeof AdminCommunicationsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/reminders/': typeof AdminRemindersIndexRoute
  '/admin/satisfaction/': typeof AdminSatisfactionIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/sales/account/': typeof SalesAccountIndexRoute
  '/sales/communications/': typeof SalesCommunicationsIndexRoute
  '/sales/opportunities/': typeof SalesOpportunitiesIndexRoute
  '/sales/reminders/': typeof SalesRemindersIndexRoute
  '/sales/satisfaction/': typeof SalesSatisfactionIndexRoute
  '/admin/client/$clientId/': typeof AdminClientClientIdIndexRoute
  '/admin/communications/$communicationId/': typeof AdminCommunicationsCommunicationIdIndexRoute
  '/admin/communications/create/': typeof AdminCommunicationsCreateIndexRoute
  '/admin/lead-and-client/clients/': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads/': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId/': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create/': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId/': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create/': typeof AdminOpportunityCreateIndexRoute
  '/admin/reminders/$reminderId/': typeof AdminRemindersReminderIdIndexRoute
  '/admin/reminders/create/': typeof AdminRemindersCreateIndexRoute
  '/admin/satisfaction/$clientId/': typeof AdminSatisfactionClientIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/admin/users/create/': typeof AdminUsersCreateIndexRoute
  '/sales/client/$clientId/': typeof SalesClientClientIdIndexRoute
  '/sales/communications/$communicationId/': typeof SalesCommunicationsCommunicationIdIndexRoute
  '/sales/communications/create/': typeof SalesCommunicationsCreateIndexRoute
  '/sales/lead-and-client/clients/': typeof SalesLeadAndClientClientsIndexRoute
  '/sales/lead-and-client/leads/': typeof SalesLeadAndClientLeadsIndexRoute
  '/sales/lead/$leadId/': typeof SalesLeadLeadIdIndexRoute
  '/sales/opportunity/$opportunityId/': typeof SalesOpportunityOpportunityIdIndexRoute
  '/sales/opportunity/create/': typeof SalesOpportunityCreateIndexRoute
  '/sales/reminders/$reminderId/': typeof SalesRemindersReminderIdIndexRoute
  '/sales/reminders/create/': typeof SalesRemindersCreateIndexRoute
  '/sales/satisfaction/$clientId/': typeof SalesSatisfactionClientIdIndexRoute
  '/admin/opportunity/$opportunityId/edit/': typeof AdminOpportunityOpportunityIdEditIndexRoute
  '/sales/opportunity/$opportunityId/edit/': typeof SalesOpportunityOpportunityIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sales': typeof SalesRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/sales/lead-and-client': typeof SalesLeadAndClientRouteRouteWithChildren
  '/survey/$token': typeof SurveyTokenRoute
  '/login': typeof LoginIndexRoute
  '/admin/account': typeof AdminAccountIndexRoute
  '/admin/audit-log': typeof AdminAuditLogIndexRoute
  '/admin/communications': typeof AdminCommunicationsIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
  '/admin/reminders': typeof AdminRemindersIndexRoute
  '/admin/satisfaction': typeof AdminSatisfactionIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/sales/account': typeof SalesAccountIndexRoute
  '/sales/communications': typeof SalesCommunicationsIndexRoute
  '/sales/opportunities': typeof SalesOpportunitiesIndexRoute
  '/sales/reminders': typeof SalesRemindersIndexRoute
  '/sales/satisfaction': typeof SalesSatisfactionIndexRoute
  '/admin/client/$clientId': typeof AdminClientClientIdIndexRoute
  '/admin/communications/$communicationId': typeof AdminCommunicationsCommunicationIdIndexRoute
  '/admin/communications/create': typeof AdminCommunicationsCreateIndexRoute
  '/admin/lead-and-client/clients': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create': typeof AdminOpportunityCreateIndexRoute
  '/admin/reminders/$reminderId': typeof AdminRemindersReminderIdIndexRoute
  '/admin/reminders/create': typeof AdminRemindersCreateIndexRoute
  '/admin/satisfaction/$clientId': typeof AdminSatisfactionClientIdIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/admin/users/create': typeof AdminUsersCreateIndexRoute
  '/sales/client/$clientId': typeof SalesClientClientIdIndexRoute
  '/sales/communications/$communicationId': typeof SalesCommunicationsCommunicationIdIndexRoute
  '/sales/communications/create': typeof SalesCommunicationsCreateIndexRoute
  '/sales/lead-and-client/clients': typeof SalesLeadAndClientClientsIndexRoute
  '/sales/lead-and-client/leads': typeof SalesLeadAndClientLeadsIndexRoute
  '/sales/lead/$leadId': typeof SalesLeadLeadIdIndexRoute
  '/sales/opportunity/$opportunityId': typeof SalesOpportunityOpportunityIdIndexRoute
  '/sales/opportunity/create': typeof SalesOpportunityCreateIndexRoute
  '/sales/reminders/$reminderId': typeof SalesRemindersReminderIdIndexRoute
  '/sales/reminders/create': typeof SalesRemindersCreateIndexRoute
  '/sales/satisfaction/$clientId': typeof SalesSatisfactionClientIdIndexRoute
  '/admin/opportunity/$opportunityId/edit': typeof AdminOpportunityOpportunityIdEditIndexRoute
  '/sales/opportunity/$opportunityId/edit': typeof SalesOpportunityOpportunityIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sales': typeof SalesRouteRouteWithChildren
  '/admin/lead-and-client': typeof AdminLeadAndClientRouteRouteWithChildren
  '/sales/lead-and-client': typeof SalesLeadAndClientRouteRouteWithChildren
  '/survey/$token': typeof SurveyTokenRoute
  '/login/': typeof LoginIndexRoute
  '/admin/account/': typeof AdminAccountIndexRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
  '/admin/communications/': typeof AdminCommunicationsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/reminders/': typeof AdminRemindersIndexRoute
  '/admin/satisfaction/': typeof AdminSatisfactionIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/sales/account/': typeof SalesAccountIndexRoute
  '/sales/communications/': typeof SalesCommunicationsIndexRoute
  '/sales/opportunities/': typeof SalesOpportunitiesIndexRoute
  '/sales/reminders/': typeof SalesRemindersIndexRoute
  '/sales/satisfaction/': typeof SalesSatisfactionIndexRoute
  '/admin/client/$clientId/': typeof AdminClientClientIdIndexRoute
  '/admin/communications/$communicationId/': typeof AdminCommunicationsCommunicationIdIndexRoute
  '/admin/communications/create/': typeof AdminCommunicationsCreateIndexRoute
  '/admin/lead-and-client/clients/': typeof AdminLeadAndClientClientsIndexRoute
  '/admin/lead-and-client/leads/': typeof AdminLeadAndClientLeadsIndexRoute
  '/admin/lead/$leadId/': typeof AdminLeadLeadIdIndexRoute
  '/admin/lead/create/': typeof AdminLeadCreateIndexRoute
  '/admin/opportunity/$opportunityId/': typeof AdminOpportunityOpportunityIdIndexRoute
  '/admin/opportunity/create/': typeof AdminOpportunityCreateIndexRoute
  '/admin/reminders/$reminderId/': typeof AdminRemindersReminderIdIndexRoute
  '/admin/reminders/create/': typeof AdminRemindersCreateIndexRoute
  '/admin/satisfaction/$clientId/': typeof AdminSatisfactionClientIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/admin/users/create/': typeof AdminUsersCreateIndexRoute
  '/sales/client/$clientId/': typeof SalesClientClientIdIndexRoute
  '/sales/communications/$communicationId/': typeof SalesCommunicationsCommunicationIdIndexRoute
  '/sales/communications/create/': typeof SalesCommunicationsCreateIndexRoute
  '/sales/lead-and-client/clients/': typeof SalesLeadAndClientClientsIndexRoute
  '/sales/lead-and-client/leads/': typeof SalesLeadAndClientLeadsIndexRoute
  '/sales/lead/$leadId/': typeof SalesLeadLeadIdIndexRoute
  '/sales/opportunity/$opportunityId/': typeof SalesOpportunityOpportunityIdIndexRoute
  '/sales/opportunity/create/': typeof SalesOpportunityCreateIndexRoute
  '/sales/reminders/$reminderId/': typeof SalesRemindersReminderIdIndexRoute
  '/sales/reminders/create/': typeof SalesRemindersCreateIndexRoute
  '/sales/satisfaction/$clientId/': typeof SalesSatisfactionClientIdIndexRoute
  '/admin/opportunity/$opportunityId/edit/': typeof AdminOpportunityOpportunityIdEditIndexRoute
  '/sales/opportunity/$opportunityId/edit/': typeof SalesOpportunityOpportunityIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sales'
    | '/admin/lead-and-client'
    | '/sales/lead-and-client'
    | '/survey/$token'
    | '/login/'
    | '/admin/account/'
    | '/admin/audit-log/'
    | '/admin/communications/'
    | '/admin/dashboard/'
    | '/admin/opportunities/'
    | '/admin/reminders/'
    | '/admin/satisfaction/'
    | '/admin/users/'
    | '/sales/account/'
    | '/sales/communications/'
    | '/sales/opportunities/'
    | '/sales/reminders/'
    | '/sales/satisfaction/'
    | '/admin/client/$clientId/'
    | '/admin/communications/$communicationId/'
    | '/admin/communications/create/'
    | '/admin/lead-and-client/clients/'
    | '/admin/lead-and-client/leads/'
    | '/admin/lead/$leadId/'
    | '/admin/lead/create/'
    | '/admin/opportunity/$opportunityId/'
    | '/admin/opportunity/create/'
    | '/admin/reminders/$reminderId/'
    | '/admin/reminders/create/'
    | '/admin/satisfaction/$clientId/'
    | '/admin/users/$userId/'
    | '/admin/users/create/'
    | '/sales/client/$clientId/'
    | '/sales/communications/$communicationId/'
    | '/sales/communications/create/'
    | '/sales/lead-and-client/clients/'
    | '/sales/lead-and-client/leads/'
    | '/sales/lead/$leadId/'
    | '/sales/opportunity/$opportunityId/'
    | '/sales/opportunity/create/'
    | '/sales/reminders/$reminderId/'
    | '/sales/reminders/create/'
    | '/sales/satisfaction/$clientId/'
    | '/admin/opportunity/$opportunityId/edit/'
    | '/sales/opportunity/$opportunityId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/sales'
    | '/admin/lead-and-client'
    | '/sales/lead-and-client'
    | '/survey/$token'
    | '/login'
    | '/admin/account'
    | '/admin/audit-log'
    | '/admin/communications'
    | '/admin/dashboard'
    | '/admin/opportunities'
    | '/admin/reminders'
    | '/admin/satisfaction'
    | '/admin/users'
    | '/sales/account'
    | '/sales/communications'
    | '/sales/opportunities'
    | '/sales/reminders'
    | '/sales/satisfaction'
    | '/admin/client/$clientId'
    | '/admin/communications/$communicationId'
    | '/admin/communications/create'
    | '/admin/lead-and-client/clients'
    | '/admin/lead-and-client/leads'
    | '/admin/lead/$leadId'
    | '/admin/lead/create'
    | '/admin/opportunity/$opportunityId'
    | '/admin/opportunity/create'
    | '/admin/reminders/$reminderId'
    | '/admin/reminders/create'
    | '/admin/satisfaction/$clientId'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/sales/client/$clientId'
    | '/sales/communications/$communicationId'
    | '/sales/communications/create'
    | '/sales/lead-and-client/clients'
    | '/sales/lead-and-client/leads'
    | '/sales/lead/$leadId'
    | '/sales/opportunity/$opportunityId'
    | '/sales/opportunity/create'
    | '/sales/reminders/$reminderId'
    | '/sales/reminders/create'
    | '/sales/satisfaction/$clientId'
    | '/admin/opportunity/$opportunityId/edit'
    | '/sales/opportunity/$opportunityId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sales'
    | '/admin/lead-and-client'
    | '/sales/lead-and-client'
    | '/survey/$token'
    | '/login/'
    | '/admin/account/'
    | '/admin/audit-log/'
    | '/admin/communications/'
    | '/admin/dashboard/'
    | '/admin/opportunities/'
    | '/admin/reminders/'
    | '/admin/satisfaction/'
    | '/admin/users/'
    | '/sales/account/'
    | '/sales/communications/'
    | '/sales/opportunities/'
    | '/sales/reminders/'
    | '/sales/satisfaction/'
    | '/admin/client/$clientId/'
    | '/admin/communications/$communicationId/'
    | '/admin/communications/create/'
    | '/admin/lead-and-client/clients/'
    | '/admin/lead-and-client/leads/'
    | '/admin/lead/$leadId/'
    | '/admin/lead/create/'
    | '/admin/opportunity/$opportunityId/'
    | '/admin/opportunity/create/'
    | '/admin/reminders/$reminderId/'
    | '/admin/reminders/create/'
    | '/admin/satisfaction/$clientId/'
    | '/admin/users/$userId/'
    | '/admin/users/create/'
    | '/sales/client/$clientId/'
    | '/sales/communications/$communicationId/'
    | '/sales/communications/create/'
    | '/sales/lead-and-client/clients/'
    | '/sales/lead-and-client/leads/'
    | '/sales/lead/$leadId/'
    | '/sales/opportunity/$opportunityId/'
    | '/sales/opportunity/create/'
    | '/sales/reminders/$reminderId/'
    | '/sales/reminders/create/'
    | '/sales/satisfaction/$clientId/'
    | '/admin/opportunity/$opportunityId/edit/'
    | '/sales/opportunity/$opportunityId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SalesRouteRoute: typeof SalesRouteRouteWithChildren
  SurveyTokenRoute: typeof SurveyTokenRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lead-and-client': {
      id: '/admin/lead-and-client'
      path: '/lead-and-client'
      fullPath: '/admin/lead-and-client'
      preLoaderRoute: typeof AdminLeadAndClientRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/lead-and-client': {
      id: '/sales/lead-and-client'
      path: '/lead-and-client'
      fullPath: '/sales/lead-and-client'
      preLoaderRoute: typeof SalesLeadAndClientRouteRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/survey/$token': {
      id: '/survey/$token'
      path: '/survey/$token'
      fullPath: '/survey/$token'
      preLoaderRoute: typeof SurveyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account/': {
      id: '/admin/account/'
      path: '/account'
      fullPath: '/admin/account/'
      preLoaderRoute: typeof AdminAccountIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log/': {
      id: '/admin/audit-log/'
      path: '/audit-log'
      fullPath: '/admin/audit-log/'
      preLoaderRoute: typeof AdminAuditLogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications/': {
      id: '/admin/communications/'
      path: '/communications'
      fullPath: '/admin/communications/'
      preLoaderRoute: typeof AdminCommunicationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/opportunities'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reminders/': {
      id: '/admin/reminders/'
      path: '/reminders'
      fullPath: '/admin/reminders/'
      preLoaderRoute: typeof AdminRemindersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/satisfaction/': {
      id: '/admin/satisfaction/'
      path: '/satisfaction'
      fullPath: '/admin/satisfaction/'
      preLoaderRoute: typeof AdminSatisfactionIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/sales/account/': {
      id: '/sales/account/'
      path: '/account'
      fullPath: '/sales/account/'
      preLoaderRoute: typeof SalesAccountIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/communications/': {
      id: '/sales/communications/'
      path: '/communications'
      fullPath: '/sales/communications/'
      preLoaderRoute: typeof SalesCommunicationsIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/opportunities/': {
      id: '/sales/opportunities/'
      path: '/opportunities'
      fullPath: '/sales/opportunities/'
      preLoaderRoute: typeof SalesOpportunitiesIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/reminders/': {
      id: '/sales/reminders/'
      path: '/reminders'
      fullPath: '/sales/reminders/'
      preLoaderRoute: typeof SalesRemindersIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/satisfaction/': {
      id: '/sales/satisfaction/'
      path: '/satisfaction'
      fullPath: '/sales/satisfaction/'
      preLoaderRoute: typeof SalesSatisfactionIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/admin/client/$clientId/': {
      id: '/admin/client/$clientId/'
      path: '/client/$clientId'
      fullPath: '/admin/client/$clientId/'
      preLoaderRoute: typeof AdminClientClientIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications/$communicationId/': {
      id: '/admin/communications/$communicationId/'
      path: '/communications/$communicationId'
      fullPath: '/admin/communications/$communicationId/'
      preLoaderRoute: typeof AdminCommunicationsCommunicationIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications/create/': {
      id: '/admin/communications/create/'
      path: '/communications/create'
      fullPath: '/admin/communications/create/'
      preLoaderRoute: typeof AdminCommunicationsCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lead-and-client/clients/': {
      id: '/admin/lead-and-client/clients/'
      path: '/clients'
      fullPath: '/admin/lead-and-client/clients/'
      preLoaderRoute: typeof AdminLeadAndClientClientsIndexRouteImport
      parentRoute: typeof AdminLeadAndClientRouteRoute
    }
    '/admin/lead-and-client/leads/': {
      id: '/admin/lead-and-client/leads/'
      path: '/leads'
      fullPath: '/admin/lead-and-client/leads/'
      preLoaderRoute: typeof AdminLeadAndClientLeadsIndexRouteImport
      parentRoute: typeof AdminLeadAndClientRouteRoute
    }
    '/admin/lead/$leadId/': {
      id: '/admin/lead/$leadId/'
      path: '/lead/$leadId'
      fullPath: '/admin/lead/$leadId/'
      preLoaderRoute: typeof AdminLeadLeadIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lead/create/': {
      id: '/admin/lead/create/'
      path: '/lead/create'
      fullPath: '/admin/lead/create/'
      preLoaderRoute: typeof AdminLeadCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunity/$opportunityId/': {
      id: '/admin/opportunity/$opportunityId/'
      path: '/opportunity/$opportunityId'
      fullPath: '/admin/opportunity/$opportunityId/'
      preLoaderRoute: typeof AdminOpportunityOpportunityIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/opportunity/create/': {
      id: '/admin/opportunity/create/'
      path: '/opportunity/create'
      fullPath: '/admin/opportunity/create/'
      preLoaderRoute: typeof AdminOpportunityCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reminders/$reminderId/': {
      id: '/admin/reminders/$reminderId/'
      path: '/reminders/$reminderId'
      fullPath: '/admin/reminders/$reminderId/'
      preLoaderRoute: typeof AdminRemindersReminderIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reminders/create/': {
      id: '/admin/reminders/create/'
      path: '/reminders/create'
      fullPath: '/admin/reminders/create/'
      preLoaderRoute: typeof AdminRemindersCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/satisfaction/$clientId/': {
      id: '/admin/satisfaction/$clientId/'
      path: '/satisfaction/$clientId'
      fullPath: '/admin/satisfaction/$clientId/'
      preLoaderRoute: typeof AdminSatisfactionClientIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/create/': {
      id: '/admin/users/create/'
      path: '/users/create'
      fullPath: '/admin/users/create/'
      preLoaderRoute: typeof AdminUsersCreateIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/sales/client/$clientId/': {
      id: '/sales/client/$clientId/'
      path: '/client/$clientId'
      fullPath: '/sales/client/$clientId/'
      preLoaderRoute: typeof SalesClientClientIdIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/communications/$communicationId/': {
      id: '/sales/communications/$communicationId/'
      path: '/communications/$communicationId'
      fullPath: '/sales/communications/$communicationId/'
      preLoaderRoute: typeof SalesCommunicationsCommunicationIdIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/communications/create/': {
      id: '/sales/communications/create/'
      path: '/communications/create'
      fullPath: '/sales/communications/create/'
      preLoaderRoute: typeof SalesCommunicationsCreateIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/lead-and-client/clients/': {
      id: '/sales/lead-and-client/clients/'
      path: '/clients'
      fullPath: '/sales/lead-and-client/clients/'
      preLoaderRoute: typeof SalesLeadAndClientClientsIndexRouteImport
      parentRoute: typeof SalesLeadAndClientRouteRoute
    }
    '/sales/lead-and-client/leads/': {
      id: '/sales/lead-and-client/leads/'
      path: '/leads'
      fullPath: '/sales/lead-and-client/leads/'
      preLoaderRoute: typeof SalesLeadAndClientLeadsIndexRouteImport
      parentRoute: typeof SalesLeadAndClientRouteRoute
    }
    '/sales/lead/$leadId/': {
      id: '/sales/lead/$leadId/'
      path: '/lead/$leadId'
      fullPath: '/sales/lead/$leadId/'
      preLoaderRoute: typeof SalesLeadLeadIdIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/opportunity/$opportunityId/': {
      id: '/sales/opportunity/$opportunityId/'
      path: '/opportunity/$opportunityId'
      fullPath: '/sales/opportunity/$opportunityId/'
      preLoaderRoute: typeof SalesOpportunityOpportunityIdIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/opportunity/create/': {
      id: '/sales/opportunity/create/'
      path: '/opportunity/create'
      fullPath: '/sales/opportunity/create/'
      preLoaderRoute: typeof SalesOpportunityCreateIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/reminders/$reminderId/': {
      id: '/sales/reminders/$reminderId/'
      path: '/reminders/$reminderId'
      fullPath: '/sales/reminders/$reminderId/'
      preLoaderRoute: typeof SalesRemindersReminderIdIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/reminders/create/': {
      id: '/sales/reminders/create/'
      path: '/reminders/create'
      fullPath: '/sales/reminders/create/'
      preLoaderRoute: typeof SalesRemindersCreateIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/sales/satisfaction/$clientId/': {
      id: '/sales/satisfaction/$clientId/'
      path: '/satisfaction/$clientId'
      fullPath: '/sales/satisfaction/$clientId/'
      preLoaderRoute: typeof SalesSatisfactionClientIdIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
    '/admin/opportunity/$opportunityId/edit/': {
      id: '/admin/opportunity/$opportunityId/edit/'
      path: '/opportunity/$opportunityId/edit'
      fullPath: '/admin/opportunity/$opportunityId/edit/'
      preLoaderRoute: typeof AdminOpportunityOpportunityIdEditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/sales/opportunity/$opportunityId/edit/': {
      id: '/sales/opportunity/$opportunityId/edit/'
      path: '/opportunity/$opportunityId/edit'
      fullPath: '/sales/opportunity/$opportunityId/edit/'
      preLoaderRoute: typeof SalesOpportunityOpportunityIdEditIndexRouteImport
      parentRoute: typeof SalesRouteRoute
    }
  }
}

interface AdminLeadAndClientRouteRouteChildren {
  AdminLeadAndClientClientsIndexRoute: typeof AdminLeadAndClientClientsIndexRoute
  AdminLeadAndClientLeadsIndexRoute: typeof AdminLeadAndClientLeadsIndexRoute
}

const AdminLeadAndClientRouteRouteChildren: AdminLeadAndClientRouteRouteChildren =
  {
    AdminLeadAndClientClientsIndexRoute: AdminLeadAndClientClientsIndexRoute,
    AdminLeadAndClientLeadsIndexRoute: AdminLeadAndClientLeadsIndexRoute,
  }

const AdminLeadAndClientRouteRouteWithChildren =
  AdminLeadAndClientRouteRoute._addFileChildren(
    AdminLeadAndClientRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminLeadAndClientRouteRoute: typeof AdminLeadAndClientRouteRouteWithChildren
  AdminAccountIndexRoute: typeof AdminAccountIndexRoute
  AdminAuditLogIndexRoute: typeof AdminAuditLogIndexRoute
  AdminCommunicationsIndexRoute: typeof AdminCommunicationsIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
  AdminRemindersIndexRoute: typeof AdminRemindersIndexRoute
  AdminSatisfactionIndexRoute: typeof AdminSatisfactionIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminClientClientIdIndexRoute: typeof AdminClientClientIdIndexRoute
  AdminCommunicationsCommunicationIdIndexRoute: typeof AdminCommunicationsCommunicationIdIndexRoute
  AdminCommunicationsCreateIndexRoute: typeof AdminCommunicationsCreateIndexRoute
  AdminLeadLeadIdIndexRoute: typeof AdminLeadLeadIdIndexRoute
  AdminLeadCreateIndexRoute: typeof AdminLeadCreateIndexRoute
  AdminOpportunityOpportunityIdIndexRoute: typeof AdminOpportunityOpportunityIdIndexRoute
  AdminOpportunityCreateIndexRoute: typeof AdminOpportunityCreateIndexRoute
  AdminRemindersReminderIdIndexRoute: typeof AdminRemindersReminderIdIndexRoute
  AdminRemindersCreateIndexRoute: typeof AdminRemindersCreateIndexRoute
  AdminSatisfactionClientIdIndexRoute: typeof AdminSatisfactionClientIdIndexRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
  AdminUsersCreateIndexRoute: typeof AdminUsersCreateIndexRoute
  AdminOpportunityOpportunityIdEditIndexRoute: typeof AdminOpportunityOpportunityIdEditIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLeadAndClientRouteRoute: AdminLeadAndClientRouteRouteWithChildren,
  AdminAccountIndexRoute: AdminAccountIndexRoute,
  AdminAuditLogIndexRoute: AdminAuditLogIndexRoute,
  AdminCommunicationsIndexRoute: AdminCommunicationsIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
  AdminRemindersIndexRoute: AdminRemindersIndexRoute,
  AdminSatisfactionIndexRoute: AdminSatisfactionIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminClientClientIdIndexRoute: AdminClientClientIdIndexRoute,
  AdminCommunicationsCommunicationIdIndexRoute:
    AdminCommunicationsCommunicationIdIndexRoute,
  AdminCommunicationsCreateIndexRoute: AdminCommunicationsCreateIndexRoute,
  AdminLeadLeadIdIndexRoute: AdminLeadLeadIdIndexRoute,
  AdminLeadCreateIndexRoute: AdminLeadCreateIndexRoute,
  AdminOpportunityOpportunityIdIndexRoute:
    AdminOpportunityOpportunityIdIndexRoute,
  AdminOpportunityCreateIndexRoute: AdminOpportunityCreateIndexRoute,
  AdminRemindersReminderIdIndexRoute: AdminRemindersReminderIdIndexRoute,
  AdminRemindersCreateIndexRoute: AdminRemindersCreateIndexRoute,
  AdminSatisfactionClientIdIndexRoute: AdminSatisfactionClientIdIndexRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
  AdminUsersCreateIndexRoute: AdminUsersCreateIndexRoute,
  AdminOpportunityOpportunityIdEditIndexRoute:
    AdminOpportunityOpportunityIdEditIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SalesLeadAndClientRouteRouteChildren {
  SalesLeadAndClientClientsIndexRoute: typeof SalesLeadAndClientClientsIndexRoute
  SalesLeadAndClientLeadsIndexRoute: typeof SalesLeadAndClientLeadsIndexRoute
}

const SalesLeadAndClientRouteRouteChildren: SalesLeadAndClientRouteRouteChildren =
  {
    SalesLeadAndClientClientsIndexRoute: SalesLeadAndClientClientsIndexRoute,
    SalesLeadAndClientLeadsIndexRoute: SalesLeadAndClientLeadsIndexRoute,
  }

const SalesLeadAndClientRouteRouteWithChildren =
  SalesLeadAndClientRouteRoute._addFileChildren(
    SalesLeadAndClientRouteRouteChildren,
  )

interface SalesRouteRouteChildren {
  SalesLeadAndClientRouteRoute: typeof SalesLeadAndClientRouteRouteWithChildren
  SalesAccountIndexRoute: typeof SalesAccountIndexRoute
  SalesCommunicationsIndexRoute: typeof SalesCommunicationsIndexRoute
  SalesOpportunitiesIndexRoute: typeof SalesOpportunitiesIndexRoute
  SalesRemindersIndexRoute: typeof SalesRemindersIndexRoute
  SalesSatisfactionIndexRoute: typeof SalesSatisfactionIndexRoute
  SalesClientClientIdIndexRoute: typeof SalesClientClientIdIndexRoute
  SalesCommunicationsCommunicationIdIndexRoute: typeof SalesCommunicationsCommunicationIdIndexRoute
  SalesCommunicationsCreateIndexRoute: typeof SalesCommunicationsCreateIndexRoute
  SalesLeadLeadIdIndexRoute: typeof SalesLeadLeadIdIndexRoute
  SalesOpportunityOpportunityIdIndexRoute: typeof SalesOpportunityOpportunityIdIndexRoute
  SalesOpportunityCreateIndexRoute: typeof SalesOpportunityCreateIndexRoute
  SalesRemindersReminderIdIndexRoute: typeof SalesRemindersReminderIdIndexRoute
  SalesRemindersCreateIndexRoute: typeof SalesRemindersCreateIndexRoute
  SalesSatisfactionClientIdIndexRoute: typeof SalesSatisfactionClientIdIndexRoute
  SalesOpportunityOpportunityIdEditIndexRoute: typeof SalesOpportunityOpportunityIdEditIndexRoute
}

const SalesRouteRouteChildren: SalesRouteRouteChildren = {
  SalesLeadAndClientRouteRoute: SalesLeadAndClientRouteRouteWithChildren,
  SalesAccountIndexRoute: SalesAccountIndexRoute,
  SalesCommunicationsIndexRoute: SalesCommunicationsIndexRoute,
  SalesOpportunitiesIndexRoute: SalesOpportunitiesIndexRoute,
  SalesRemindersIndexRoute: SalesRemindersIndexRoute,
  SalesSatisfactionIndexRoute: SalesSatisfactionIndexRoute,
  SalesClientClientIdIndexRoute: SalesClientClientIdIndexRoute,
  SalesCommunicationsCommunicationIdIndexRoute:
    SalesCommunicationsCommunicationIdIndexRoute,
  SalesCommunicationsCreateIndexRoute: SalesCommunicationsCreateIndexRoute,
  SalesLeadLeadIdIndexRoute: SalesLeadLeadIdIndexRoute,
  SalesOpportunityOpportunityIdIndexRoute:
    SalesOpportunityOpportunityIdIndexRoute,
  SalesOpportunityCreateIndexRoute: SalesOpportunityCreateIndexRoute,
  SalesRemindersReminderIdIndexRoute: SalesRemindersReminderIdIndexRoute,
  SalesRemindersCreateIndexRoute: SalesRemindersCreateIndexRoute,
  SalesSatisfactionClientIdIndexRoute: SalesSatisfactionClientIdIndexRoute,
  SalesOpportunityOpportunityIdEditIndexRoute:
    SalesOpportunityOpportunityIdEditIndexRoute,
}

const SalesRouteRouteWithChildren = SalesRouteRoute._addFileChildren(
  SalesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SalesRouteRoute: SalesRouteRouteWithChildren,
  SurveyTokenRoute: SurveyTokenRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
